### ISSUE TITLE
PRCI reports success when tests did not execute because controller VM was down

### ISSUE THREAD

**Issue by wladich** [freeipa/freeipa-pr-ci#327] opened 2019-12-04 12:57 UTC
Runner log: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/3a2d4c7a-1693-11ea-9ea9-fa163ed18b41/runner.log.gz

This was executed on my own runner. For some reason controller VM was down during `vagrant ssh` but the reported status of the tests is "success"

**Comment by wladich** [comment] 2019-12-04 13:28
The VM was paused because no space left on the disk.

**Comment by flo-renaud** [comment] 2020-06-02 08:59
Also saw the same issue with PR #[219](https://github.com/freeipa-pr-ci2/freeipa/pull/219), with the test `simple_replication` for instance. The test is displayed as successful in PR#219 but the test failed, see [runner.log](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/a7c774d8-a426-11ea-8432-fa163e623825/runner.log.gz).

@f-trivino the issue should be investigated ASAP as the displayed test status is not reliable.

**Comment by f-trivino** [comment] 2020-06-02 09:16
Hi @flo-renaud thanks for reporting. This is high priority as we might merge content that it is not tested at all.

**Comment by f-trivino** [comment] 2020-06-02 09:25
after a quick look, looks like the issue is due to a prci service restart in the middle of a job run when deploying changes. Let's keep an eye on gating workflows, if happens again then it will be critical.

**Comment by netoarmando** [comment] 2020-07-20 20:03
Fixed by https://github.com/freeipa/freeipa-pr-ci/pull/372, thus closing this. Please re-open it if you feel it necessary.

**Closed by netoarmando** 2020-07-20 20:03 UTC
