### ISSUE TITLE
Failure to spawn ssh on Windows

### ISSUE THREAD

**Issue by fcami** [freeipa/freeipa-pr-ci#368] opened 2020-05-29 07:37 UTC
test_trust failed with:
```
2020-05-28 11:41:54,339    DEBUG  fatal: [ad-root]: FAILED! => {"can_pause_and_continue": false, "changed": false, "depended_by": [], "dependencies": ["tcpip"], "description": "", "desktop_interact": false, "display_name": "CYGWIN cygsshd", "exists": true, "msg": "Failed to start service 'CYGWIN cygsshd (cygsshd)'.", "name": "cygsshd", "path": "C:\\tools\\cygwin\\bin\\cygrunsrv.exe", "start_mode": "auto", "state": "stopped", "username": "LocalSystem"}
```
full [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/2ffd801c-a0d6-11ea-834e-fa163e34ae64/), [PR](https://github.com/freeipa-pr-ci2/freeipa/pull/210)

**Comment by netoarmando** [comment] 2020-11-10 00:05
It seems the issue is not observed any more, thus closing this.

**Closed by netoarmando** 2020-11-10 00:05 UTC
