### ISSUE TITLE
RunPytest: show how many test passed / failed in status description

### ISSUE THREAD

**Issue by tomaskrizek** [freeipa/freeipa-pr-ci#17] opened 2017-07-28 10:54 UTC
When RunPytest is executed, it currently reports `<no description>` back to github commit status. It'd be better if it showed how many test passed or failed. If there is a pytest error, a short error message (perhaps with the exit code) could be displayed.

**Comment by f-trivino** [comment] 2019-05-24 12:22
We see this ticket as duplicate of “Make the success status more informative #178”. We are closing this ticket in favour of #178 since it is more descriptive and includes more details on how to address this improvement.

**Closed by f-trivino** 2019-05-24 12:22 UTC
Labels: difficulty:normal, groomed, prio:low, type:feature
