### ISSUE TITLE
vagrant  killed with SIGTERM, result is green

### ISSUE THREAD

**Issue by wladich** [freeipa/freeipa-pr-ci#356] opened 2020-03-20 11:21 UTC
The build: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/4753cdd0-6a66-11ea-ac60-fa163e3ad6c5/runner.log.gz

Several problems here:
1. Somebody killed `vagrant provision` with SIGTERM.
2.  repeated provisioning totally failed but reported success in status code:
```
2020-03-20 05:03:46,160     INFO  Executing: Process "vagrant provision"
2020-03-20 05:03:52,822    DEBUG  ==> controller: Domain is not running. Please run `vagrant up` or `vagrant resume` first.
2020-03-20 05:03:52,967    DEBUG  ==> ad-root: Domain is not running. Please run `vagrant up` or `vagrant resume` first.
2020-03-20 05:03:53,134    DEBUG  ==> ad-child: Domain is not running. Please run `vagrant up` or `vagrant resume` first.
2020-03-20 05:03:53,265    DEBUG  ==> ad-tree: Domain is not running. Please run `vagrant up` or `vagrant resume` first.
2020-03-20 05:03:53,430    DEBUG  ==> master: Domain is not running. Please run `vagrant up` or `vagrant resume` first.
2020-03-20 05:03:53,571    DEBUG  ==> client0: Domain is not running. Please run `vagrant up` or `vagrant resume` first.
```
3. Tests did not run but no problems reported:
```
2020-03-20 05:03:53,680     INFO  Executing: Process "vagrant ssh -c IPATEST_YAML_CONFIG=/vagrant/ipa-test-config.yaml ipa-run-tests test_integration/test_trust.py --verbose --logging-level=debug --logfile-dir=/vagrant/ --html=/vagrant/report.html --junit-xml=/vagrant/junit.xml"
2020-03-20 05:03:57,097    DEBUG  ==> controller: Domain is not running. Please run `vagrant up` or `vagrant resume` first.
2020-03-20 05:03:57,111     INFO  >>>>> TESTS PASSED <<<<<<
```

**Comment by netoarmando** [comment] 2020-06-04 00:03
Duplicate of https://github.com/freeipa/freeipa-pr-ci/issues/327.

**Comment by netoarmando** [comment] 2020-07-20 20:05
Fixed by https://github.com/freeipa/freeipa-pr-ci/pull/372, thus closing this. Please re-open it if you feel it necessary.

**Closed by netoarmando** 2020-07-20 20:05 UTC
